### ISSUE TITLE
More commit expected

### ISSUE THREAD

**Issue by alfredhot** [songxue77/reactjs_study#1]
Hi, I'm your big fan! 
I like your hair and your eye color!

Please, make more and more commit on this awesome repo!
make your profile page be covered by green mosaic!

best regard

**Comment by songxue77** [comment]
"From start to give up" season 1, welcome!

I need a react based free admin template, do you have one?

**Comment by alfredhot** [comment]
> "From start to give up" season 1, welcome!
> 
> I need a react based free admin template, do you have one?

yeah! 
Actually, I found a crowd of~ 
[Look at this...](https://github.com/search?q=react+admin)

I hope it helps.
regard.
